version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start --inspect=0.0.0.0:9229
    environment:
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=root
    ports:
      - 4000:4000
    networks:
      - net
    depends_on:
      - db
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    platform: linux/amd64
    ports:
      - 3306:3306
    environment:
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=root
    networks:
      - net
    volumes:
      - ./data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d

networks:
  net: